SELECT 
'|' || TABLE_NAME || '|' || TRIGGER_NAME  || '|' || TRIGGER_TYPE  || '|' || TRIGGERING_EVENT  || '|'  c1

FROM SYS.ALL_TRIGGERS

WHERE  TABLE_NAME IN (
  SELECT TABLE_NAME FROM ALL_TABLES
  WHERE  TABLESPACE_NAME = 'VICKY'
  and TABLE_NAME > 'AQ'
  )
  ORDER BY TABLE_NAME
;

select 
'|' || SEQUENCE_NAME || '|' || MIN_VALUE || '|' || MAX_VALUE || '|' || CACHE_SIZE || '|' || LAST_NUMBER ||'|'
  from SYS.ALL_SEQUENCES
where sequence_owner = 'VIC'
;
