-- SQL/VENTAS
-- VTA_RECIBOS.SQL


CREATE TABLE  "VTA_RECIBOS" 
   (	
    "ID" NUMBER(*,0) NOT NULL ENABLE, 
	"FECHA" DATE, 
	"CAB_VENTAS_ID" NUMBER, 
	"PUNTO_VENTA" NUMBER(*,0), 
	"NRO_CAB" NUMBER(*,0), 
	"CLIENTE_ID" NUMBER, 
	"CLI_DFISCAL_ID" NUMBER, 
	"TOTAL" NUMBER(*,2), 
	"OBS" VARCHAR2(400), 
	"CREATED" DATE, 
	"CREATED_BY" VARCHAR2(200), 
	"UPDATED" DATE, 
	"UPDATED_BY" VARCHAR2(200), 
	 CONSTRAINT "VTA_RECIBOS_PK" PRIMARY KEY ("ID") ENABLE
   )
/
ALTER TABLE  "VTA_RECIBOS" ADD CONSTRAINT "VTA_RECIBOS_FK1" FOREIGN KEY ("CLIENTE_ID")
	  REFERENCES  "CLI" ("ID") ENABLE
/
ALTER TABLE  "VTA_RECIBOS" ADD CONSTRAINT "VTA_RECIBOS_FK2" FOREIGN KEY ("CAB_VENTAS_ID")
	  REFERENCES  "CAB_VENTAS" ("ID") ENABLE
/

CREATE OR REPLACE TRIGGER  "TRG_VTA_RECIBOS_NEW" 
	BEFORE INSERT ON  "VTA_RECIBOS" 
	FOR EACH ROW 
BEGIN  
   IF INSERTING THEN 
      IF :NEW."ID" IS NULL THEN 
         SELECT SEQ_VTA_RECIBOS.NEXTVAL INTO :NEW."ID" FROM DUAL; 
      END IF; 
    :NEW.CREATED := SYSDATE;
    :NEW.CREATED_BY := NVL(V('APP_USER'),USER);      
      
   END IF; 
END;
/
ALTER TRIGGER  "TRG_VTA_RECIBOS_NEW" ENABLE
/

CREATE OR REPLACE TRIGGER  "TRG_VTA_RECIBOS_UPD" 
	BEFORE UPDATE ON VTA_RECIBOS 
	FOR EACH ROW 
BEGIN
    :NEW.UPDATED := SYSDATE;
    :NEW.UPDATED_BY := NVL(V('APP_USER'),USER);   
END;
/
ALTER TRIGGER  "TRG_VTA_RECIBOS_UPD" ENABLE
/
