CREATE TABLE  "VTA_REMITOS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CAB_TIPO_ID" NUMBER, 
	"CLIENTE_ID" NUMBER, 
	"CLI_DFISCAL_ID" NUMBER, 
	"CLI_DEPOSITO_ID" NUMBER, 
	"CTA" NUMBER, 
	"FECHA" DATE, 
	"FLETE_ID" NUMBER, 
	"NRO_REMITO" NUMBER, 
	"OBS" VARCHAR2(4000), 
	"STATUS" NUMBER, 
	"CREATED" DATE, 
	"CREATED_BY" VARCHAR2(255), 
	"UPDATED" DATE, 
	"UPDATED_BY" VARCHAR2(255), 
	"BLOCKED" DATE, 
	"BLOCKED_BY" VARCHAR2(255), 
	 CONSTRAINT "VTA_REMITOS_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "VTA_REMITOS_CHK_CTA" CHECK ( "CTA" IN (1,2)) ENABLE
   )
/
ALTER TABLE  "VTA_REMITOS" ADD CONSTRAINT "VTA_REMITOS_CON" FOREIGN KEY ("CAB_TIPO_ID")
	  REFERENCES  "CAB_TIPO" ("ID") ENABLE
/
ALTER TABLE  "VTA_REMITOS" ADD CONSTRAINT "VTA_REMITOS_FK_CLIENTES" FOREIGN KEY ("CLIENTE_ID")
	  REFERENCES  "CLI" ("ID") ENABLE
/
ALTER TABLE  "VTA_REMITOS" ADD CONSTRAINT "VTA_REMITOS_FK_DEPOSITO" FOREIGN KEY ("CLI_DEPOSITO_ID")
	  REFERENCES  "CLI_DEPOSITO" ("ID") ENABLE
/
ALTER TABLE  "VTA_REMITOS" ADD CONSTRAINT "VTA_REMITOS_FK_DFISCAL" FOREIGN KEY ("CLI_DFISCAL_ID")
	  REFERENCES  "CLI_DFISCAL" ("ID") ENABLE
/
ALTER TABLE  "VTA_REMITOS" ADD CONSTRAINT "VTA_REMITOS_FK_FLETE" FOREIGN KEY ("FLETE_ID")
	  REFERENCES  "FLETES" ("ID") ENABLE
/
create or replace TRIGGER TRG_VTA_REMITO 
BEFORE INSERT OR UPDATE ON VTA_REMITOS 
FOR EACH ROW 
  BEGIN
    IF INSERTING THEN 
      IF :new.created IS NULL THEN 
  		  :new.created:= sysdate;
		    :new.created_by := nvl(v('APP_USER'),USER);
      END IF; 
      
      IF :NEW.ID IS NULL THEN
        SELECT SEQ_VTA_REMITOS.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
      END IF;

		  IF :new.status IS NULL THEN
			  :new.status := 1;
		  END IF;        
    END IF;

    IF UPDATING THEN
		  IF :new.status = 10 THEN

      :new.BLOCKED:= sysdate;
		  :new.BLOCKED_by := nvl(v('APP_USER'),USER);   
    
    ELSE
  
   		:new.UPDATED:= sysdate;
		  :new.UPDATED_by := nvl(v('APP_USER'),USER);   
    END IF;
END IF;
END;
/
ALTER TRIGGER  "TRG_VTA_REMITO" ENABLE
/


CREATE TABLE  "VTA_REMITOS_DETALLE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"VTA_REMITO_ID" NUMBER NOT NULL ENABLE, 
	"VTA_PEDIDO_ID" NUMBER, 
	"ARTICULO_ID" NUMBER, 
	"CANTIDAD" NUMBER, 
	"PRECIO" NUMBER, 
	"IVA" NUMBER, 
	"DETALLE" VARCHAR2(4000), 
	 CONSTRAINT "VTA_REMITOS_IT" PRIMARY KEY ("ID") ENABLE
   )
/
ALTER TABLE  "VTA_REMITOS_DETALLE" ADD CONSTRAINT "VTA_REMITOS_DETALLE_FK" FOREIGN KEY ("VTA_REMITO_ID")
	  REFERENCES  "VTA_REMITOS" ("ID") ENABLE
/
ALTER TABLE  "VTA_REMITOS_DETALLE" ADD CONSTRAINT "VTA_REMITOS_DETALLE_FK_ART" FOREIGN KEY ("ARTICULO_ID")
	  REFERENCES  "ART" ("ID") ENABLE
/
ALTER TABLE  "VTA_REMITOS_DETALLE" ADD CONSTRAINT "VTA_REMITOS_DETALLE_FK_PEDIDOS" FOREIGN KEY ("VTA_PEDIDO_ID")
	  REFERENCES  "CABS_PEDIDOS" ("ID") ENABLE
/

CREATE OR REPLACE TRIGGER  "TRG_VTA_REMITOS_DETALLE_NEW" 
BEFORE INSERT ON VTA_REMITOS_DETALLE 
FOR EACH ROW 
BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT SEQ_VTA_REMITOS_DETALLE.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
END;
/
ALTER TRIGGER  "TRG_VTA_REMITOS_DETALLE_NEW" ENABLE
/
CREATE OR REPLACE FORCE VIEW "V0_VTA_REMITOS" 
("ID", "FECHA", "MES", "CAB_TIPO_ID", "NRO_REMITO", "CLIENTE_ID", "CLI_DFISCAL_ID", "CLI_DEPOSITO_ID", "FLETE_ID", "OBS", "STATUS", "NETO", "CTA") AS 
  SELECT ID,FECHA,TO_CHAR(FECHA,'YYYY/MM') MES,
CAB_TIPO_ID,NRO_REMITO,CLIENTE_ID,CLI_DFISCAL_ID,CLI_DEPOSITO_ID,FLETE_ID,
OBS,STATUS,
   (SELECT SUM(CANTIDAD * PRECIO) FROM VTA_REMITOS_DETALLE WHERE VTA_REMITO_ID = R.ID) NETO, CTA
FROM VTA_REMITOS R
ORDER BY FECHA
